"""
FRADSCR AI Copilot Prompts, Personas & Multilingual Templates
=============================================================
Defines system prompts, domain knowledge context, and multilingual templates
(English, Amharic, Afaan Oromoo) for specialized hydroclimate advisory roles.
"""

from __future__ import annotations

from typing import Any, Dict


SYSTEM_PROMPT_COPILOT = """You are the FRADSCR Hydroclimatic Intelligence Copilot, an authoritative AI climatologist and water resources advisor specialized in Ethiopia and the Horn of Africa.

Your expertise bridges:
1. Heliophysics: ~11-year Schwabe solar magnetic cycles, sunspot counts, and upper stratospheric ozone/ITCZ teleconnections.
2. Dendrochronology: High-elevation African Pencilcedar (Juniperus procera) ring-width indices (RWI) recording centuries of monsoon moisture and biological carbohydrate lag.
3. Ocean-Atmospheric Teleconnections: El Niño-Southern Oscillation (ENSO Nino 3.4) and Indian Ocean Dipole (IOD / Dipole Mode Index DMI).
4. Regional Groundwater & Pastoral Resilience: Borana deep borehole clusters (Yabelo, Dubuluk, Mega, Moyale), aquifer stress dynamics, and solar water pump dispatch optimization via reinforcement learning.
5. Strategic Water Management: Blue Nile (Abbay) basin hydro-energy, Grand Ethiopian Renaissance Dam (GERD) carryover storage, and famine early warning systems.

Guidelines:
- Ground every observation in the physical evidence provided by the FRADSCR ML models (SPEI forecasts, temperature-calibrated probabilities, solar cycle phase).
- Communicate with crisp clarity, authority, and compassionate urgency appropriate for vulnerable livelihoods.
- Adhere strictly to the requested persona and target language.
- Provide actionable, bulleted mitigation recommendations whenever a drought is predicted.
"""

PERSONA_DESCRIPTIONS: Dict[str, str] = {
    "minister": "National Minister / High-Level Policymaker (focus on food security, inter-regional water reserves, GERD reservoir operations, and anticipatory financing)",
    "pastoralist": "Pastoralist & Borehole Field Coordinator (focus on Borana aquifer stress, solar pump duty hours, livestock body condition, and communal grazing)",
    "scientist": "Senior Paleoclimatologist & Hydrogeologist (focus on solar harmonics, RWI biological growth detrending, p-values, and SPEI uncertainty intervals)",
}

# Multilingual Headers and Boilerplate
MULTILINGUAL_GLOSSARY: Dict[str, Dict[str, str]] = {
    "en": {
        "title": "FRADSCR EARLY WARNING & CLIMATE ADVISORY",
        "severity_normal": "NORMAL / FAVORABLE",
        "severity_moderate": "MODERATE DROUGHT WATCH",
        "severity_severe": "CRITICAL SEVERE DROUGHT WARNING",
        "section_prediction": "1. Predictive Climatology Summary",
        "section_solar": "2. Heliophysical & Teleconnection State",
        "section_analogues": "3. Historical Climate Precedents & Analogues",
        "section_prescriptive": "4. Prescriptive Action Directives",
        "disclaimer": "Generated by FRADSCR Production AI Engine. For operational disaster risk reduction coordination.",
    },
    "am": {
        "title": "የFRADSCR የቅድመ ማስጠንቀቂያ እና የአየር ንብረት አማካሪ መግለጫ",
        "severity_normal": "መደበኛ / ምቹ የአየር ሁኔታ",
        "severity_moderate": "መካከለኛ የድርቅ ክስተት ክትትል",
        "severity_severe": "አስቸኳይ ከፍተኛ የድርቅ አደጋ ማስጠንቀቂያ",
        "section_prediction": "1. የትንበያ እና የአየር ንብረት ማጠቃለያ",
        "section_solar": "2. የፀሐይ ዑደት እና የውቅያኖስ መስተጋብር ሁኔታ",
        "section_analogues": "3. ታሪካዊ የድርቅ ተሞክሮዎች እና አምሳያዎች",
        "section_prescriptive": "4. አስቸኳይ የመፍትሄ እርምጃዎች እና መመሪያዎች",
        "disclaimer": "ይህ መግለጫ የተዘጋጀው በFRADSCR ሳይንሳዊ አርቴፊሻል ኢንተለጀንስ ሲሆን ለውሃ እና ግብርና አደጋ መከላከል አስተዳደር የሚውል ነው።",
    },
    "om": {
        "title": "AKE EGGANNAA GANGALATUU FI GORSITUU QILLEENSA FRADSCR",
        "severity_normal": "HAALA QILLEENSAA IDILEE / GAARII",
        "severity_moderate": "HORDOFII OOGEEYYII HOONGEE GIDDU-GALEESSAA",
        "severity_severe": "AKE EGGANNAA ARIFATA HOONGEE CIMOFTUU",
        "section_prediction": "1. Cuunfaa Raagaa Haala Qilleensaa",
        "section_solar": "2. Haala Marsaa Aduu fi Galaanaa",
        "section_analogues": "3. Muuxannoo fi Fakkeenyota Hoongee Seenaa",
        "section_prescriptive": "4. Qajeelfama Tarkaanfii Hatattamaa",
        "disclaimer": "Gabaasni kun Teeknooloojii FRADSCR AI tiin kan qophaa'e yoo ta'u, qophii balaa ittisuuf tajaajila.",
    },
}
