services:
  # Streamlit Advisory Application
  - type: web
    name: fradscr-drought-predictor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    domains:
      - fradscr.pro.et
      - www.fradscr.pro.et
    envVars:
      - key: PORT
        value: 8501
      - key: CALIBRATION_TEMPERATURE
        value: "0.35"
