services:
  # ----------------------------------------------------------------------------
  # 1. 3D WebGL Digital Twin & FastAPI Microservice
  # ----------------------------------------------------------------------------
  - type: web
    name: fradscr-3d-api
    runtime: docker
    dockerfilePath: ./Dockerfile.ml
    plan: starter
    region: frankfurt
    envVars:
      - key: PORT
        value: 8000
      - key: CALIBRATION_TEMPERATURE
        value: "0.35"

  # ----------------------------------------------------------------------------
  # 2. Streamlit Advisory Application Hub
  # ----------------------------------------------------------------------------
  - type: web
    name: fradscr-drought-predictor
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    domains:
      - fradscr.pro.et
      - www.fradscr.pro.et
    envVars:
      - key: PORT
        value: 8501
      - key: CALIBRATION_TEMPERATURE
        value: "0.35"
